# Generated by Django 3.1.4 on 2021-01-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20210105_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='watchlist',
        ),
    ]
