# Generated by Django 3.1.4 on 2021-01-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('original_title', models.CharField(max_length=200, verbose_name='Título Original')),
                ('image_url', models.URLField(verbose_name='Imagem')),
                ('overview', models.TextField(verbose_name='Descrição')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Avaliação')),
                ('adult', models.BooleanField(default='', verbose_name='Filme Adulto')),
                ('original_language', models.CharField(max_length=10, verbose_name='Idioma Original')),
                ('popularity', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Popularidade')),
                ('vote_count', models.IntegerField(verbose_name='Quantidade de avaliações')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_watch', models.BooleanField(default=False, verbose_name='Filme na Watchlist?')),
                ('watched', models.BooleanField(default=False, verbose_name='Filme assistido?')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist', to='filmes.filmes', verbose_name='Filme')),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlist',
            },
        ),
    ]
