# Generated by Django 3.1.4 on 2020-12-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filmes',
        ),
    ]
