# Generated by Django 3.1.4 on 2021-01-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_filmes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='slug',
        ),
    ]
