# Generated by Django 3.1.4 on 2021-01-05 13:27

from django.db import migrations, transaction
import os
import requests

API_KEY = '9818d68778070a69dfffaf497d206c6b'
url = 'https://api.themoviedb.org/3/movie/popular?api_key={0}&language=pt-br&page=1'.format(API_KEY)
r = requests.get(url)
data = r.json()

def create_data(apps, schema_editor):
    Filmes = apps.get_model('filmes', 'Filmes')
    with transaction.atomic():
        for i in range(len(data['results'])-1):
            Filmes(
                title = data['results'][i]['title'],
                original_title = data['results'][i]['original_title'],
                image_url = 'https://image.tmdb.org/t/p/w500/' + data['results'][i]['poster_path'],
                overview = data['results'][i]['overview'],
                release_date = data['results'][i]['release_date'],
                vote_average = data['results'][i]['vote_average'],
                adult = data['results'][i]['adult'],
                original_language = data['results'][i]['original_language'],
                popularity = data['results'][i]['popularity'],
                vote_count = data['results'][i]['vote_count']
            ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
