# Generated by Django 3.1.4 on 2021-01-05 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filmes', '0003_remove_filmes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='to_watch',
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_watch', models.BooleanField(default=False, verbose_name='Filme na Watchlist?')),
                ('watched', models.BooleanField(default=False, verbose_name='Filme assistido?')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist', to='filmes.filmes', verbose_name='Filme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlist',
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
