# Generated by Django 3.1.4 on 2021-01-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_auto_20210105_1027'),
        ('filmes', '0003_filmes'),
    ]

    operations = [
    ]
