# Generated by Django 3.1.4 on 2021-01-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_remove_perfil_watchlist'),
        ('filmes', '0004_merge_20210105_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist', to='perfil.perfil', verbose_name='Perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('perfil', 'movie')},
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
    ]
