# Generated by Django 3.1.4 on 2021-01-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(null=True, verbose_name='Data de Nascimento'),
        ),
    ]
