# Generated by Django 3.1.4 on 2021-01-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210105_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='perfil',
        ),
    ]
