# Generated by Django 3.1.4 on 2021-01-05 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_remove_perfil_user'),
        ('usuarios', '0003_remove_user_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Perfil', to='perfil.perfil', verbose_name='Usuário'),
        ),
    ]
